### ISSUE TITLE
Solicitação de contribuição

### ISSUE THREAD

**Issue by tiagohermano** [araucarialab/p5.js-website#2]
Olá, eu assisti a live 'noite de processing' e tomei conhecimento do projeto por lá. 
Quero muito contribuir! :nerd_face: 
Conforme comentado na live sobre a necessidade de ajuda para traduzir a parte de exemplos, eu gostaria de pegar a tradução dos exemplos da categoria `Structure` 
![image](https://user-images.githubusercontent.com/5157960/127247728-4868ee77-b3d0-4e06-84fe-ab5887ba69ee.png)

**Comment by mardefronteira** [comment]
Massa, @tiagohermano! Manda ver! :)

**Comment by tiagohermano** [comment]
@mardefronteira estou fazendo a tradução aos poucos de forma iterativa. O PR já está aberto para que sugestões e correções sejam feitas

**Comment by tiagohermano** [comment]
O PR está finalizado, aguardo revisão :)
