### ISSUE TITLE
Slight language code change

### ISSUE THREAD

**Issue by limzykenneth** [araucarialab/p5.js-website#4]
Hi all,

Thanks for getting the updates in for the reference JSON file, I'm currently working on integrating it to the Pontoon system.

Just a small request from me, I noticed you have listed the language code for your project as `pt-br` I wonder is it alright to slightly adjust it to `pt-BR`, just to match capitalization used in Pontoon. It's not a big deal if not, just let me know.

**Comment by jlbrsl** [comment]
Hi!  Sorry for the delayed response. 
I've seen you made the adjustment, its fine! 
Also, thanks you for setting up the Pontoon system, i've just signed up and it look really good.
